import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {sidebar_options} from '@/constants/sidebar'
import Link from 'next/link'
import Image from 'next/image'
import {AiFillHome} from 'react-icons/ai'
import { IconType } from 'react-icons'

const inter = Inter({ subsets: ['latin'] })

const image = "https://pbs.twimg.com/profile_images/1658306244577472513/up-Oc-FT_400x400.jpg"

console.log(sidebar_options)

export const metadata: Metadata = {
  icons: {
    icon: image
  },
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='w-full flex justify-center'>
        <div className='lg:w-2/3 flex p-2 py-5'>
          <div className='w-[20%] py-7 flex flex-col text-xl font-semibold opacity-90 gap-3'>
            <Image className='rounded-full'
            src={image}
            width={69}
            height={69}
            alt='Image'
            />
            {
              sidebar_options.map((op, index) => {
                const IconComponent: IconType = op.icon
                return (
                  <div key={index}>
                  <Link href={op.route} className='w-fit flex gap-3 p-3 px-5 rounded-full backdrop-blur-sm  hover:bg-slate-300/25'>
                    <IconComponent className='relative top-1'/>
                    {op.name}
                  </Link>
                </div>
                )
              })
            }
          </div>
          <div className='w-[50%] border border-white'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}